import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import Header from './components/Header';

import './globals.css'
import '../assets/css/bootstrap.min.css'
import '../assets/css/icon-font.min.css'
import '../assets/css/plugins.css'
import '../assets/css/helper.css'
import '../assets/css/style.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    
   

<>

 <html lang="en">
      <body className={inter.className}>
        


  <meta charSet="utf-8" />
  <meta httpEquiv="x-ua-compatible" content="ie=edge" />
  <title>Jadusona - eCommerce Baby shop Bootstrap5 Template</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {/* Favicon */}
  <link
    rel="shortcut icon"
    type="image/x-icon"
    href="assets/images/favicon.ico"
  />
  {/* CSS
	============================================ */}
 
  {/* Modernizer JS */}
  <div className="main-wrapper">
    {/* Header Section Start */}
    <Header />

      
    
    {/* Header Section End */}
    
    {/* Hero Section Start */}
    <div className="hero-section section">
      {/* Hero Slider Start */}
      <div className="hero-slider hero-slider-one fix">
        {/* Hero Item Start */}
        <div
          className="hero-item"
          style={{ backgroundImage: "url(assets/images/hero/hero-1.jpg)" }}
        >
          {/* Hero Content */}
          <div className="hero-content">
            <h1>
              Get 35% off <br />
              Latest Baby Product
            </h1>
            <a href="#">SHOP NOW</a>
          </div>
        </div>
        {/* Hero Item End */}
        {/* Hero Item Start */}
        <div
          className="hero-item"
          style={{ backgroundImage: "url(assets/images/hero/hero-2.jpg)" }}
        >
          {/* Hero Content */}
          <div className="hero-content">
            <h1>
              Get 35% off <br />
              Latest Baby Product
            </h1>
            <a href="#">SHOP NOW</a>
          </div>
        </div>
        {/* Hero Item End */}
      </div>
      {/* Hero Slider End */}
    </div>
    {/* Hero Section End */}
    {/* Banner Section Start */}
    <div className="banner-section section mt-40">
      <div className="container-fluid">
        <div className="row row-10 mbn-20">
          <div className="col-lg-4 col-md-6 col-12 mb-20">
            <div className="banner banner-1 content-left content-middle">
              <a href="#" className="image">
                <img
                  src="assets/images/banner/banner-1.jpg"
                  alt="Banner Image"
                />
              </a>
              <div className="content">
                <h1>
                  New Arrival <br />
                  Baby’s Shoe <br />
                  GET 30% OFF
                </h1>
                <a href="#" data-hover="SHOP NOW">
                  SHOP NOW
                </a>
              </div>
            </div>
          </div>
          <div className="col-lg-4 col-md-6 col-12 mb-20">
            <a href="#" className="banner banner-2">
              <img src="assets/images/banner/banner-2.jpg" alt="Banner Image" />
              <div className="content bg-theme-one">
                <h1>New Toy’s for your Baby</h1>
              </div>
              <span className="banner-offer">25% off</span>
            </a>
          </div>
          <div className="col-lg-4 col-md-6 col-12 mb-20">
            <div className="banner banner-1 content-left content-top">
              <a href="#" className="image">
                <img
                  src="assets/images/banner/banner-3.jpg"
                  alt="Banner Image"
                />
              </a>
              <div className="content">
                <h1>
                  Trendy <br />
                  Collections
                </h1>
                <a href="#" data-hover="SHOP NOW">
                  SHOP NOW
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Banner Section End */}
    {/* Product Section Start */}
    <div className="product-section section section-padding">
      <div className="container">
        <div className="row">
          <div className="section-title text-center col mb-30">
            <h1>Popular Products</h1>
            <p>All popular product find here</p>
          </div>
        </div>
        <div className="row mbn-40">
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-1.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Tmart Baby Dress</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                      <i className="fa fa-star-o" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$25</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-2.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Jumpsuit Outfits</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$09</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-3.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Smart Shirt</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-o" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$18</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-4.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Kids Shoe</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                      <i className="fa fa-star-o" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$15</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-5.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html"> Bowknot Bodysuit</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$12</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-6.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Striped T-Shirt</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-o" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$12</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-7.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Kislen Jak Tops</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$29</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-3 col-lg-4 col-md-6 col-12 mb-40">
            <div className="product-item">
              <div className="product-inner">
                <div className="image">
                  <img src="assets/images/product/product-8.jpg" alt="Image" />
                  <div className="image-overlay">
                    <div className="action-buttons">
                      <button>add to cart</button>
                      <button>add to wishlist</button>
                    </div>
                  </div>
                </div>
                <div className="content">
                  <div className="content-left">
                    <h4 className="title">
                      <a href="single-product.html">Lattic Shirt</a>
                    </h4>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-o" />
                    </div>
                    <h5 className="size">
                      Size: <span>S</span>
                      <span>M</span>
                      <span>L</span>
                      <span>XL</span>
                    </h5>
                    <h5 className="color">
                      Color: <span style={{ backgroundColor: "#ffb2b0" }} />
                      <span style={{ backgroundColor: "#0271bc" }} />
                      <span style={{ backgroundColor: "#efc87c" }} />
                      <span style={{ backgroundColor: "#00c183" }} />
                    </h5>
                  </div>
                  <div className="content-right">
                    <span className="price">$08</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Product Section End */}
    {/* Banner Section Start */}
    <div className="banner-section section section-padding pt-0 fix">
      <div className="row row-5 mbn-10">
        <div className="col-lg-4 col-md-6 col-12 mb-10">
          <div className="banner banner-3">
            <a href="#" className="image">
              <img src="assets/images/banner/banner-4.jpg" alt="Banner Image" />
            </a>
            <div
              className="content"
              style={{
                backgroundImage: "url(assets/images/banner/banner-3-shape.png)"
              }}
            >
              <h1>New Arrivals</h1>
              <h2>Up to 35% off</h2>
              <h4>2 - 5 Years</h4>
            </div>
            <a href="#" className="shop-link" data-hover="SHOP NOW">
              SHOP NOW
            </a>
          </div>
        </div>
        <div className="col-lg-4 col-md-6 col-12 mb-10">
          <div className="banner banner-4">
            <a href="#" className="image">
              <img src="assets/images/banner/banner-5.jpg" alt="Banner Image" />
            </a>
            <div className="content">
              <div className="content-inner">
                <h1>Online Shopping</h1>
                <h2>
                  Flat 25% off <br />
                  New Trend for 2022
                </h2>
                <a href="#" data-hover="SHOP NOW">
                  SHOP NOW
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="col-lg-4 col-md-6 col-12 mb-10">
          <div className="banner banner-5">
            <a href="#" className="image">
              <img src="assets/images/banner/banner-6.jpg" alt="Banner Image" />
            </a>
            <div
              className="content"
              style={{
                backgroundImage: "url(assets/images/banner/banner-5-shape.png)"
              }}
            >
              <h1>
                Collection for <br />
                Baby Girl’s
              </h1>
              <h2>Flat 25% off</h2>
            </div>
            <a href="#" className="shop-link" data-hover="SHOP NOW">
              SHOP NOW
            </a>
          </div>
        </div>
      </div>
    </div>
    {/* Banner Section End */}
    {/* Product Section Start */}
    <div className="product-section section section-padding pt-0">
      <div className="container">
        <div className="row mbn-40">
          <div className="col-lg-4 col-md-6 col-12 mb-40">
            <div className="row">
              <div className="section-title text-start col mb-30">
                <h1>Best Deal</h1>
                <p>Exclusive deals for you</p>
              </div>
            </div>
            <div className="best-deal-slider w-100">
              <div className="slide-item">
                <div className="best-deal-product">
                  <div className="image">
                    <img
                      src="assets/images/product/best-deal-1.jpg"
                      alt="Image"
                    />
                  </div>
                  <div className="content-top">
                    <div className="content-top-left">
                      <h4 className="title">
                        <a href="#">2 Piece Shirt Set</a>
                      </h4>
                      <div className="ratting">
                        <i className="fa fa-star" />
                        <i className="fa fa-star" />
                        <i className="fa fa-star" />
                        <i className="fa fa-star" />
                        <i className="fa fa-star-half-o" />
                      </div>
                    </div>
                    <div className="content-top-right">
                      <span className="price">
                        $13 <span className="old">$28</span>
                      </span>
                    </div>
                  </div>
                  <div className="content-bottom">
                    <div className="countdown" data-countdown="2023/06/20" />
                    <a href="#" data-hover="SHOP NOW">
                      SHOP NOW
                    </a>
                  </div>
                </div>
              </div>
              <div className="slide-item">
                <div className="best-deal-product">
                  <div className="image">
                    <img
                      src="assets/images/product/best-deal-2.jpg"
                      alt="Image"
                    />
                  </div>
                  <div className="content-top">
                    <div className="content-top-left">
                      <h4 className="title">
                        <a href="#">Kelly Shirt Set</a>
                      </h4>
                      <div className="ratting">
                        <i className="fa fa-star" />
                        <i className="fa fa-star" />
                        <i className="fa fa-star" />
                        <i className="fa fa-star" />
                        <i className="fa fa-star-o" />
                      </div>
                    </div>
                    <div className="content-top-right">
                      <span className="price">
                        $09 <span className="old">$25</span>
                      </span>
                    </div>
                  </div>
                  <div className="content-bottom">
                    <div className="countdown" data-countdown="2023/06/20" />
                    <a href="#" data-hover="SHOP NOW">
                      SHOP NOW
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-lg-8 col-md-6 col-12 ps-3 ps-lg-4 ps-xl-5 mb-40">
            <div className="row">
              <div className="section-title text-start col mb-30">
                <h1>On Sale Products</h1>
                <p>All featured product find here</p>
              </div>
            </div>
            <div className="small-product-slider row row-7 mbn-40">
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-1.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Skily Girld Dress</a>
                    </h4>
                    <span className="price">
                      $19 <span className="old">$35</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                      <i className="fa fa-star-o" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-2.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Kelly Shirt Set</a>
                    </h4>
                    <span className="price">
                      $08 <span className="old">$25</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-o" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-3.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Sleeveless Tops</a>
                    </h4>
                    <span className="price">
                      $05 <span className="old">$12</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-4.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Babysuit Bundle</a>
                    </h4>
                    <span className="price">
                      $25 <span className="old">$45</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-5.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Xshuai Baby Frock</a>
                    </h4>
                    <span className="price">
                      $13 <span className="old">$28</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-6.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Stylish Hat</a>
                    </h4>
                    <span className="price">
                      $03 <span className="old">$10</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                      <i className="fa fa-star-o" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-7.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Aolvo Kids Munch</a>
                    </h4>
                    <span className="price">
                      $25 <span className="old">$35</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                      <i className="fa fa-star-o" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col mb-40">
                <div className="on-sale-product">
                  <a href="single-product.html" className="image">
                    <img
                      src="assets/images/product/on-sale-8.jpg"
                      alt="Image"
                    />
                  </a>
                  <div className="content text-center">
                    <h4 className="title">
                      <a href="single-product.html">Tmart Baby Dress</a>
                    </h4>
                    <span className="price">
                      $48 <span className="old">$65</span>
                    </span>
                    <div className="ratting">
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star" />
                      <i className="fa fa-star-half-o" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Product Section End */}
    {/* Feature Section Start */}
    <div
      className="feature-section bg-theme-two section section-padding fix"
      style={{ backgroundImage: "url(assets/images/pattern/pattern-dot.png)" }}
    >
      <div className="container">
        <div className="feature-wrap row justify-content-between mbn-30">
          <div className="col-md-4 col-12 mb-30">
            <div className="feature-item text-center">
              <div className="icon">
                <img src="assets/images/feature/feature-1.png" alt="Image" />
              </div>
              <div className="content">
                <h3>Free Shipping</h3>
                <p>Start from $100</p>
              </div>
            </div>
          </div>
          <div className="col-md-4 col-12 mb-30">
            <div className="feature-item text-center">
              <div className="icon">
                <img src="assets/images/feature/feature-2.png" alt="Image" />
              </div>
              <div className="content">
                <h3>Money Back Guarantee</h3>
                <p>Back within 25 days</p>
              </div>
            </div>
          </div>
          <div className="col-md-4 col-12 mb-30">
            <div className="feature-item text-center">
              <div className="icon">
                <img src="assets/images/feature/feature-3.png" alt="Image" />
              </div>
              <div className="content">
                <h3>Secure Payment</h3>
                <p>Payment Security</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Feature Section End */}
    {/* Blog Section Start */}
    <div className="blog-section section section-padding">
      <div className="container">
        <div className="row mbn-40">
          <div className="col-xl-6 col-lg-5 col-12 mb-40">
            <div className="row">
              <div className="section-title text-start col mb-30">
                <h1>CLIENTS REVIEW</h1>
                <p>Clients says abot us</p>
              </div>
            </div>
            <div className="row mbn-40">
              <div className="col-12 mb-40">
                <div className="testimonial-item">
                  <p>
                    Jadusona is one of the most exclusive Baby shop in the wold,
                    where you can find all product for your baby that your want
                    to buy for your baby. I recomanded this shop all of you
                  </p>
                  <div className="testimonial-author">
                    <img
                      src="assets/images/testimonial/testimonial-1.png"
                      alt="Image"
                    />
                    <div className="content">
                      <h4>Zacquline Smith</h4>
                      <p>CEO, Momens Group</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-12 mb-40">
                <div className="testimonial-item">
                  <p>
                    Jadusona is one of the most exclusive Baby shop in the wold,
                    where you can find all product for your baby that your want
                    to buy for your baby. I recomanded this shop all of you
                  </p>
                  <div className="testimonial-author">
                    <img
                      src="assets/images/testimonial/testimonial-2.png"
                      alt="Image"
                    />
                    <div className="content">
                      <h4>Nusaha Williams</h4>
                      <p>CEO, Momens Group</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-xl-6 col-lg-7 col-12 mb-40">
            <div className="row">
              <div className="section-title text-start col mb-30">
                <h1>FROM THE BLOG</h1>
                <p>Find all latest update here</p>
              </div>
            </div>
            <div className="row mbn-40">
              <div className="col-12 mb-40">
                <div className="blog-item">
                  <div className="image-wrap">
                    <h4 className="date">
                      May <span>25</span>
                    </h4>
                    <a className="image" href="single-blog.html">
                      <img src="assets/images/blog/blog-1.jpg" alt="Image" />
                    </a>
                  </div>
                  <div className="content">
                    <h4 className="title">
                      <a href="single-blog.html">
                        Lates and new Trens for baby fashion
                      </a>
                    </h4>
                    <div className="desc">
                      <p>
                        Jadusona is one of the most of a exclusive Baby shop in
                        the
                      </p>
                    </div>
                    <ul className="meta">
                      <li>
                        <a href="#">
                          <img
                            src="assets/images/blog/blog-author-1.jpg"
                            alt="Blog Author"
                          />
                          Muhin
                        </a>
                      </li>
                      <li>
                        <a href="#">25 Likes</a>
                      </li>
                      <li>
                        <a href="#">05 Views</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="col-12 mb-40">
                <div className="blog-item">
                  <div className="image-wrap">
                    <h4 className="date">
                      May <span>20</span>
                    </h4>
                    <a className="image" href="single-blog.html">
                      <img src="assets/images/blog/blog-2.jpg" alt="Image" />
                    </a>
                  </div>
                  <div className="content">
                    <h4 className="title">
                      <a href="single-blog.html">
                        New Collection New Trend all New Style
                      </a>
                    </h4>
                    <div className="desc">
                      <p>
                        Jadusona is one of the most of a exclusive Baby shop in
                        the
                      </p>
                    </div>
                    <ul className="meta">
                      <li>
                        <a href="#">
                          <img
                            src="assets/images/blog/blog-author-2.jpg"
                            alt="Blog Author"
                          />
                          Takiya
                        </a>
                      </li>
                      <li>
                        <a href="#">25 Likes</a>
                      </li>
                      <li>
                        <a href="#">05 Views</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Blog Section End */}
    {/* Brand Section Start */}
    <div className="brand-section section section-padding pt-0">
      <div className="container-fluid">
        <div className="row">
          <div className="brand-slider">
            <div className="brand-item col">
              <img src="assets/images/brands/brand-1.png" alt="Image" />
            </div>
            <div className="brand-item col">
              <img src="assets/images/brands/brand-2.png" alt="Image" />
            </div>
            <div className="brand-item col">
              <img src="assets/images/brands/brand-3.png" alt="Image" />
            </div>
            <div className="brand-item col">
              <img src="assets/images/brands/brand-4.png" alt="Image" />
            </div>
            <div className="brand-item col">
              <img src="assets/images/brands/brand-5.png" alt="Image" />
            </div>
            <div className="brand-item col">
              <img src="assets/images/brands/brand-6.png" alt="Image" />
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Brand Section End */}
    {/* Footer Top Section Start */}
    <div className="footer-top-section section bg-theme-two-light section-padding">
      <div className="container">
        <div className="row mbn-40">
          <div className="footer-widget col-lg-3 col-md-6 col-12 mb-40">
            <h4 className="title">CONTACT US</h4>
            <p>
              You address will be here
              <br /> Lorem Ipsum text
            </p>
            <p>
              <a href="tel:01234567890">01234 567 890</a>
              <a href="tel:01234567891">01234 567 891</a>
            </p>
            <p>
              <a href="mailto:info@example.com">info@example.com</a>
              <a href="#">www.example.com</a>
            </p>
          </div>
          <div className="footer-widget col-lg-3 col-md-6 col-12 mb-40">
            <h4 className="title">PRODUCTS</h4>
            <ul>
              <li>
                <a href="#">New Arrivals</a>
              </li>
              <li>
                <a href="#">Best Seller</a>
              </li>
              <li>
                <a href="#">Trendy Items</a>
              </li>
              <li>
                <a href="#">Best Deals</a>
              </li>
              <li>
                <a href="#">On Sale Products</a>
              </li>
              <li>
                <a href="#">Featured Products</a>
              </li>
            </ul>
          </div>
          <div className="footer-widget col-lg-3 col-md-6 col-12 mb-40">
            <h4 className="title">INFORMATION</h4>
            <ul>
              <li>
                <a href="#">About us</a>
              </li>
              <li>
                <a href="#">Terms &amp; Conditions</a>
              </li>
              <li>
                <a href="#">Payment Method</a>
              </li>
              <li>
                <a href="#">Product Warranty</a>
              </li>
              <li>
                <a href="#">Return Process</a>
              </li>
              <li>
                <a href="#">Payment Security</a>
              </li>
            </ul>
          </div>
          <div className="footer-widget col-lg-3 col-md-6 col-12 mb-40">
            <h4 className="title">NEWSLETTER</h4>
            <p>Subscribe our newsletter and get all update of our product</p>
            <form id="mc-form" className="mc-form footer-subscribe-form">
              <input
                id="mc-email"
                autoComplete="off"
                placeholder="Enter your email here"
                name="EMAIL"
                type="email"
              />
              <button id="mc-submit">
                <i className="fa fa-paper-plane-o" />
              </button>
            </form>
            {/* mailchimp-alerts Start */}
            <div className="mailchimp-alerts">
              <div className="mailchimp-submitting" />
              {/* mailchimp-submitting end */}
              <div className="mailchimp-success" />
              {/* mailchimp-success end */}
              <div className="mailchimp-error" />
              {/* mailchimp-error end */}
            </div>
            {/* mailchimp-alerts end */}
            <h5>FOLLOW US</h5>
            <p className="footer-social">
              <a href="#">Facebook</a> - <a href="#">Twitter</a> -{" "}
              <a href="#">Google+</a>
            </p>
          </div>
        </div>
      </div>
    </div>
    {/* Footer Top Section End */}
    {/* Footer Bottom Section Start */}
    <div className="footer-bottom-section section bg-theme-two pt-15 pb-15">
      <div className="container">
        <div className="row">
          <div className="col text-center">
            <p className="footer-copyright">
              © 2022 Jadusona. Made with{" "}
              <i className="fa fa-heart heart-icon" /> By{" "}
              <a target="_blank" href="https://hasthemes.com">
                HasThemes
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
    {/* Footer Bottom Section End */}
  </div>
  {/* JS
============================================ */}
  {/* jQuery JS */}
  {/* Migrate JS */}
  {/* Bootstrap JS */}
  {/* Plugins JS */}
  {/* Main JS */}

  {children}
        </body>
    </html>

</>


    </>
    
  )
}
