import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import Header from './components/Header';
import Footer from './components/Footer';




import './globals.css'
import '../public/assets/css/bootstrap.min.css'
import '../public/assets/css/icon-font.min.css'
import '../public/assets/css/plugins.css'
import '../public/assets/css/helper.css'
import '../public/assets/css/style.css'

import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    


 <html lang="en">
 <body className={inter.className}>      

  <meta charSet="utf-8" />
  <meta httpEquiv="x-ua-compatible" content="ie=edge" />
  <title>Jadusona - eCommerce Baby shop Bootstrap5 Template</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {/* Favicon */}
  <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.ico" />
 
  {/* Modernizer JS */}
  <div className="main-wrapper">
    {/* Header Section Start */}
    <Header />
    {/* Header Section End */}
    

    {children}


    <Footer />
    {/* Footer Bottom Section End */}
  </div>
  {/* JS
============================================ */}

<Script src="/assets/js/vendor/jquery-3.6.0.min.js" />
<Script src="/assets/js/vendor/jquery-migrate-3.3.2.min.js" />
<Script src="/assets/js/bootstrap.bundle.min.js" />
<Script src="/assets/js/plugins.js" />
<Script src="/assets/js/main.js" />

 
        </body>
    </html>

</>
    
  )
}
